##### 运行一些操作可能会导致为新结果分配内存。 例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [5]:
import torch
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
X = a + b
Y = a + b
X,Y

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [6]:
before = id(Y)
Y = Y + X
id(Y) == before

False

##### 首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新；如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

##### 我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>

In [7]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1605558635792
id(Z): 1605558635792


##### 如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销

In [8]:
before = id(X)
X += Y
id(X) == before

True

#####  torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量

In [11]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

##### 要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数

In [12]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)