In [19]:
import torch
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

##### 如果让ab相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加

In [16]:
X = a + b
X

tensor([[0, 1],
        [1, 2],
        [2, 3]])

##### 张量中的元素可以通过索引访问

In [15]:
X[-1], X[0:2]

(tensor([2, 3]),
 tensor([[0, 1],
         [1, 2]]))

##### 除读取外，我们还可以通过指定索引来将元素写入矩阵

In [18]:
X[1, 1] = 9
X

tensor([[0, 1],
        [1, 9],
        [2, 3]])